<a href="https://colab.research.google.com/github/belogabriel/modeling/blob/main/modeling_and_tuning_case5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import GridSearchCV

In [4]:
print(housing)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n-

In [3]:
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)

In [ ]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [ ]:
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [5]:
print(housing.target)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [10]:
X = housing.data
y = housing.target

# REGRESSION TECHNIQUES

1. Regressão Linear -SKLEARN-
2. Support Vector Regression (SVR) -SKLEARN-
3. Decision tree regression -XGBoost-

### Modeling Assumptions

Only numeric features

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [11]:
# TEST DESIGN
# DATASET SPLIT (20% for test)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=420)

In [18]:
# MODELING LINEAR REGRESSION

regLinear = LinearRegression().fit(X_train, y_train)
yLinear = regLinear.predict(X_test)
print(yLinear)

[1.51785447 0.46583254 2.2586307  ... 1.43195703 1.34056352 1.72030143]


In [36]:
# METRICA DE AVALIAÇÃO DOS MODELOS:
# 1. MSE E RMSE (utilizados para penalizar GRANDES erros de previsão)
# 2. Métodos SKLEARN

LinearMSE = mean_squared_error(y_test, yLinear)
LinearRMSE = np.sqrt(MSE)
print('MEAN SQUARED ERROR (MSE):', round(LinearMSE, 4))
print('-----------------------------')
print('ROOT MEAN SQUARED ERROR (RMSE):', round(LinearRMSE, 4))

MEAN SQUARED ERROR (MSE): 0.5203
-----------------------------
ROOT MEAN SQUARED ERROR (RMSE): 0.7213


In [33]:
from sklearn.svm import SVR

In [34]:
# MODELING SVR

regSVR = SVR().fit(X_train, y_train)

In [35]:
ySVR = regSVR.predict(X_test)
print(ySVR)

[1.80389824 1.78824654 1.76913604 ... 1.86371799 1.72443827 1.72694475]


In [38]:
MSE_SVR= mean_squared_error(y_test, ySVR)
RMSE_SVR = np.sqrt(MSE_SVR)

print('MEAN SQUARED ERROR (MSE):', MSE_SVR)
print('ROOT MEAN SQUARED ERROR (RMSE)', RMSE_SVR)

MEAN SQUARED ERROR (MSE): 1.3646716734385433
ROOT MEAN SQUARED ERROR (RMSE) 1.1681916253074849


In [40]:
from xgboost import XGBRegressor

In [43]:
# MODELING DECISION TREE REGRESSION

regXGB = XGBRegressor().fit(X_train, y_train)

In [45]:
yXGB = regXGB.predict(X_test)
MSEXGB = mean_squared_error(y_test, yXGB)
RMSEXGB = np.sqrt(MSEXGB)

print('MSE XGB:', MSEXGB)
print('RMSE XGB:', RMSEXGB)

MSE XGB: 0.21858315109297838
RMSE XGB: 0.46752877033716156


In [47]:
# OTIMIZAÇÃO DE HIPERPARÂMETROS (MODEL TUNING)

regXGB.get_params().keys()

dict_keys(['objective', 'base_score', 'booster', 'callbacks', 'colsample_bylevel', 'colsample_bynode', 'colsample_bytree', 'device', 'early_stopping_rounds', 'enable_categorical', 'eval_metric', 'feature_types', 'gamma', 'grow_policy', 'importance_type', 'interaction_constraints', 'learning_rate', 'max_bin', 'max_cat_threshold', 'max_cat_to_onehot', 'max_delta_step', 'max_depth', 'max_leaves', 'min_child_weight', 'missing', 'monotone_constraints', 'multi_strategy', 'n_estimators', 'n_jobs', 'num_parallel_tree', 'random_state', 'reg_alpha', 'reg_lambda', 'sampling_method', 'scale_pos_weight', 'subsample', 'tree_method', 'validate_parameters', 'verbosity'])

In [48]:
parameters = {"max_depth": [5,6,7],
              "learning_rate": [0.1,0.2,0.3],
              "objective": ['reg:squarederror'],
              "booster": ['gbtree'],
              "n_jobs": [5],
              "gamma": [0,1],
              "min_child_weight": [1,3],
              "max_delta_step": [0,1],
              "subsample": [0.5,1]
}

In [51]:
xgbGrid = GridSearchCV(XGBRegressor(), parameters, refit='neg_mean_squared_error', verbose=True).fit(X_train, y_train)

Fitting 5 folds for each of 144 candidates, totalling 720 fits


In [53]:
xgbGrid.best_params_

{'booster': 'gbtree',
 'gamma': 0,
 'learning_rate': 0.2,
 'max_delta_step': 0,
 'max_depth': 6,
 'min_child_weight': 1,
 'n_jobs': 5,
 'objective': 'reg:squarederror',
 'subsample': 1}

In [54]:
yGrid = xgbGrid.predict(X_test)

In [55]:
MSEGrid = mean_squared_error(y_test, yGrid)

In [56]:
print('MSE XGB:', MSEGrid)
print('RMSE XGB:', np.sqrt(MSEGrid))

MSE XGB: 0.21956934910329295
RMSE XGB: 0.4685822757033101
